/**
 * Survival Arts and Skill System Constants
 */

import { RealmType, CultivationArt, BattleSkill } from '../types';

export const CULTIVATION_ARTS: CultivationArt[] = [
  {
    id: 'art-basic-breath',
    name: 'Basic Breathing',
    type: 'mental',
    grade: 'C',
    description: 'Fundamental breathing patterns used by scavengers to stay calm and focused. Slightly increases exp rate.',
    realmRequirement: RealmType.QiRefining,
    cost: 0,
    effects: { expRate: 0.1 },
  },
  {
    id: 'art-iron-skin',
    name: 'Alloy Grafting',
    type: 'body',
    grade: 'C',
    description: 'A primitive method of hardening the skin through chemical washing. Permanently increases defense.',
    realmRequirement: RealmType.QiRefining,
    cost: 50,
    effects: { defense: 5, hp: 20 },
  },
  {
    id: 'art-spirit-cloud',
    name: 'Fog Protocol',
    type: 'mental',
    grade: 'C',
    description: 'A technique developed by the Iron Vanguard to stay hidden in the fog. Increases exp rate and attack.',
    realmRequirement: RealmType.QiRefining,
    cost: 100,
    sectId: 'sect-cloud',
    effects: { expRate: 0.25, attack: 5 },
  },
  {
    id: 'art-fiery-fist',
    name: 'Solar Pulse Fist',
    type: 'body',
    grade: 'B',
    description: 'Channels thermal energy into the fists. Greatly increases attack power.',
    realmRequirement: RealmType.Foundation,
    cost: 300,
    spiritualRoot: 'fire',
    effects: { attack: 30 },
  },
  {
    id: 'art-jade-bone',
    name: 'Carbon Fiber Skeleton',
    type: 'body',
    grade: 'B',
    description: 'Reinforces the bones with advanced polymers. Greatly increases vitality and defense.',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    spiritualRoot: 'earth',
    effects: { defense: 20, hp: 100 },
  },
  {
    id: 'art-pure-yang',
    name: 'Core Overload',
    type: 'mental',
    grade: 'A',
    description: 'An advanced mental state that pushes the biological core to its limits. Extremely fast progression.',
    realmRequirement: RealmType.GoldenCore,
    cost: 2000,
    spiritualRoot: 'fire',
    effects: { expRate: 0.5, attack: 50 },
  },
  {
    id: 'art-thunder-sword',
    name: 'EMP Blade Protocol',
    type: 'body',
    grade: 'A',
    description: 'Injects high-voltage pulses into melee weapons. Massive destructive power, but taxes the body.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3000,
    spiritualRoot: 'metal',
    effects: { attack: 150 },
  },
  {
    id: 'art-immortal-life',
    name: 'Bio-Regen Matrix',
    type: 'mental',
    grade: 'S',
    description: 'An ancient pre-war medical protocol that allows for rapid cellular repair and long life.',
    realmRequirement: RealmType.NascentSoul,
    cost: 8000,
    spiritualRoot: 'wood',
    effects: { expRate: 0.6, hp: 2000 },
  },
  {
    id: 'art-void-body',
    name: 'Kinetic Redirector',
    type: 'body',
    grade: 'S',
    description: 'Allows the user to phase slightly, redirecting kinetic energy. Legendary defensive and offensive capabilities.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 20000,
    effects: { defense: 500, attack: 500, hp: 5000 },
  },
  {
    id: 'art-wind-step',
    name: 'Gale Dash',
    type: 'body',
    grade: 'C',
    description: 'A swift movement technique that uses wind resistance to boost speed. Increases attack and speed.',
    realmRequirement: RealmType.QiRefining,
    cost: 80,
    effects: { attack: 8 },
  },
  {
    id: 'art-water-mirror',
    name: 'Liquid Mind',
    type: 'mental',
    grade: 'B',
    description: 'Keeps the mind calm like a still lake, helping with processing information. Increases exp rate and defense.',
    realmRequirement: RealmType.Foundation,
    cost: 400,
    spiritualRoot: 'water',
    effects: { expRate: 0.3, defense: 15 },
  },
  {
    id: 'art-earth-shield',
    name: 'Granite Skin',
    type: 'body',
    grade: 'B',
    description: 'Channels the stability of the earth to create a protective layer. Strong defensive capabilities.',
    realmRequirement: RealmType.Foundation,
    cost: 600,
    spiritualRoot: 'earth',
    effects: { defense: 40, hp: 150 },
  },
  {
    id: 'art-ice-soul',
    name: 'Cryo Soul',
    type: 'mental',
    grade: 'A',
    description: 'Freezes the emotional response, allowing for cold calculations. Greatly increases exp rate.',
    realmRequirement: RealmType.GoldenCore,
    cost: 2500,
    effects: { expRate: 0.6, defense: 30 },
  },
  {
    id: 'art-dragon-fist',
    name: 'Drake Strike',
    type: 'body',
    grade: 'A',
    description: 'A powerful heavy-hitting technique that mimics a dragon strike. Greatly increases attack power.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3500,
    effects: { attack: 200 },
  },
  {
    id: 'art-phoenix-rebirth',
    name: 'Phoenix Protocol',
    type: 'mental',
    grade: 'S',
    description: 'A high-level regeneration protocol that allows the user to emerge stronger after every breakthrough.',
    realmRequirement: RealmType.NascentSoul,
    cost: 10000,
    effects: { expRate: 0.7, hp: 3000, attack: 100 },
  },
  {
    id: 'art-star-destruction',
    name: 'Nova Burst',
    type: 'body',
    grade: 'S',
    description: 'Channels concentrated nuclear energy for a devastating strike. Extreme attack power.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 25000,
    effects: { attack: 1000, defense: 200 },
  },
  {
    id: 'art-universe-devour',
    name: 'Matter Absorber',
    type: 'mental',
    grade: 'S',
    description: 'Advanced tech that allows for the total absorption of environmental energy. Ultimate progression.',
    realmRequirement: RealmType.DaoCombining,
    cost: 50000,
    effects: { expRate: 1.0, attack: 500, defense: 500, hp: 10000 },
  },
  // Added 20 new arts
  {
    id: 'art-wooden-body',
    name: 'Fiber Skin',
    type: 'body',
    grade: 'C',
    description: 'Basic body tempering using plant-based resins. Tough as old wood.',
    realmRequirement: RealmType.QiRefining,
    cost: 60,
    effects: { defense: 8, hp: 30 },
  },
  {
    id: 'art-golden-armor',
    name: 'Scrap Plate',
    type: 'body',
    grade: 'C',
    description: 'A technique to bond scrap metal shards to the skin with aura. Decent protection.',
    realmRequirement: RealmType.QiRefining,
    cost: 120,
    effects: { defense: 15, hp: 40 },
  },
  {
    id: 'art-moonlight-refine',
    name: 'Lunar Siphon',
    type: 'mental',
    grade: 'C',
    description: 'Absorbs the cool radiation of the moon to power up your core.',
    realmRequirement: RealmType.QiRefining,
    cost: 150,
    effects: { expRate: 0.2, spirit: 5 },
  },
  {
    id: 'art-swift-shadow',
    name: 'Shadow Dash',
    type: 'body',
    grade: 'C',
    description: 'Fast movement using shadows for concealment. High speed.',
    realmRequirement: RealmType.QiRefining,
    cost: 100,
    effects: { speed: 10, attack: 5 },
  },
  {
    id: 'art-flame-palm',
    name: 'Blaze Palm',
    type: 'body',
    grade: 'B',
    description: 'Thermal energy focused into the palm. Burns through most obstacles.',
    realmRequirement: RealmType.Foundation,
    cost: 350,
    effects: { attack: 40, defense: 5 },
  },
  {
    id: 'art-frost-breath',
    name: 'Cryo Respiration',
    type: 'mental',
    grade: 'B',
    description: 'Regulates body temperature to match sub-zero environments, optimizing energy flow.',
    realmRequirement: RealmType.Foundation,
    cost: 450,
    effects: { expRate: 0.35, defense: 20 },
  },
  {
    id: 'art-iron-fist',
    name: 'Steel Knuckle',
    type: 'body',
    grade: 'B',
    description: 'Hardens the knuckles to the density of steel. Brutal force.',
    realmRequirement: RealmType.Foundation,
    cost: 550,
    effects: { attack: 50, hp: 80 },
  },
  {
    id: 'art-cloud-dance',
    name: 'Mist Weaving',
    type: 'body',
    grade: 'B',
    description: 'Fluid movement that makes you hard to track in radioactive clouds.',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    effects: { speed: 20, defense: 15 },
  },
  {
    id: 'art-storm-heart',
    name: 'Overcharged Core',
    type: 'mental',
    grade: 'B',
    description: 'Drives the energy core into an overcharged state for rapid growth.',
    realmRequirement: RealmType.Foundation,
    cost: 700,
    effects: { expRate: 0.4, attack: 20 },
  },
  {
    id: 'art-jade-armor',
    name: 'Polymer Shield',
    type: 'body',
    grade: 'B',
    description: 'Tempers the skin to have the resilience of high-grade polymers. Greatly increases defense.',
    realmRequirement: RealmType.Foundation,
    cost: 800,
    effects: { defense: 50, hp: 200 },
  },
  {
    id: 'art-sun-flame',
    name: 'Sunfire Core',
    type: 'mental',
    grade: 'A',
    description: 'Harnesses the intensity of solar radiation for rapid energy circulation.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3000,
    effects: { expRate: 0.55, attack: 80, hp: 300 },
  },
  {
    id: 'art-dark-sword',
    name: 'Vantablack Blade',
    type: 'body',
    grade: 'A',
    description: 'A stealthy combat style that absorbs light, making attacks nearly invisible.',
    realmRequirement: RealmType.GoldenCore,
    cost: 4000,
    effects: { attack: 180, speed: 30 },
  },
  {
    id: 'art-celestial-body',
    name: 'Apex Form',
    type: 'body',
    grade: 'A',
    description: 'Pushes the biological limits to achieve the perfect survived form.',
    realmRequirement: RealmType.GoldenCore,
    cost: 4500,
    effects: { defense: 120, hp: 500, attack: 100 },
  },
  {
    id: 'art-starlight-gather',
    name: 'Cosmic Collector',
    type: 'mental',
    grade: 'A',
    description: 'Collects stellar background radiation for highly efficient meditation.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3800,
    effects: { expRate: 0.65, spirit: 50 },
  },
  {
    id: 'art-soul-forge',
    name: 'Neural Refiner',
    type: 'mental',
    grade: 'A',
    description: 'Refines the neural network, vastly increasing processing power (spirit).',
    realmRequirement: RealmType.GoldenCore,
    cost: 4200,
    effects: { expRate: 0.6, spirit: 800, defense: 400 },
  },
  {
    id: 'art-divine-dragon',
    name: 'Dragon Soul Legacy',
    type: 'mental',
    grade: 'S',
    description: 'Inherited genetic data from a legendary mutant, providing massive power.',
    realmRequirement: RealmType.NascentSoul,
    cost: 12000,
    effects: { expRate: 0.75, attack: 1500, hp: 2500 },
  },
  {
    id: 'art-void-step',
    name: 'Phase Shift',
    type: 'body',
    grade: 'S',
    description: 'Allows for short-range spatial warping, making movement superlative.',
    realmRequirement: RealmType.NascentSoul,
    cost: 15000,
    effects: { speed: 3000, attack: 1200, defense: 80 },
  },
  {
    id: 'art-chaos-body',
    name: 'Quantum Form',
    type: 'body',
    grade: 'S',
    description: 'Stabilizes the body at a quantum level, reaching near-immortality.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 30000,
    effects: { defense: 8000, attack: 6000, hp: 80000 },
  },
  {
    id: 'art-dao-heart',
    name: 'Transcendental Node',
    type: 'mental',
    grade: 'S',
    description: 'Connects the mind to the universal data stream for peak progression.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 35000,
    effects: { expRate: 0.9, spirit: 2000, attack: 3000, defense: 2500 },
  },
  {
    id: 'art-immortal-awakening',
    name: 'God-Machine Awakening',
    type: 'mental',
    grade: 'S',
    description: 'Awakens the dormant pre-war AI sub-routines within the cells. Beyond human.',
    realmRequirement: RealmType.DaoCombining,
    cost: 60000,
    spiritualRoot: 'fire',
    effects: { expRate: 1.0, attack: 800, defense: 600, hp: 5000, spirit: 500 },
  },
  // Added Five-Element Arts
  {
    id: 'art-golden-sword',
    name: 'Steel Blade Focus',
    type: 'body',
    grade: 'C',
    description: 'Sharpens combat focus to an edge. Strength-based melee style.',
    realmRequirement: RealmType.QiRefining,
    cost: 90,
    spiritualRoot: 'metal',
    effects: { attack: 12, defense: 3 },
  },
  {
    id: 'art-wooden-heart',
    name: 'Bio-Sync Core',
    type: 'mental',
    grade: 'C',
    description: 'Syncs the core with biological life-cycles. Vitality-based growth.',
    realmRequirement: RealmType.QiRefining,
    cost: 70,
    spiritualRoot: 'wood',
    effects: { expRate: 0.15, hp: 25 },
  },
  {
    id: 'art-water-flow',
    name: 'Perception Stream',
    type: 'mental',
    grade: 'C',
    description: 'Fluid processing of environmental data. Perception-based growth.',
    realmRequirement: RealmType.QiRefining,
    cost: 85,
    spiritualRoot: 'water',
    effects: { expRate: 0.18, spirit: 4 },
  },
  {
    id: 'art-flame-body',
    name: 'Synaptic Overload',
    type: 'body',
    grade: 'C',
    description: 'Overclocks the nervous system for combat. Reflex-based combat.',
    realmRequirement: RealmType.QiRefining,
    cost: 95,
    spiritualRoot: 'fire',
    effects: { attack: 10, speed: 5 },
  },
  {
    id: 'art-earth-core',
    name: 'Hardened Bastion',
    type: 'body',
    grade: 'C',
    description: 'Reinforces structural integrity. Hardiness-based defensive style.',
    realmRequirement: RealmType.QiRefining,
    cost: 75,
    spiritualRoot: 'earth',
    effects: { defense: 10, hp: 35 },
  },
  {
    id: 'art-golden-protection',
    name: 'Reinforced Alloy Skin',
    type: 'body',
    grade: 'B',
    description: 'Advanced metal fiber bonding for high-impact resistance. Strength-based.',
    realmRequirement: RealmType.Foundation,
    cost: 650,
    spiritualRoot: 'metal',
    effects: { defense: 55, attack: 25 },
  },
  {
    id: 'art-wooden-rebirth',
    name: 'Nano-Repair Core',
    type: 'mental',
    grade: 'B',
    description: 'Injects nanobots into the bloodstream for continuous tissue repair. Vitality-based.',
    realmRequirement: RealmType.Foundation,
    cost: 550,
    spiritualRoot: 'wood',
    effects: { expRate: 0.35, hp: 180, defense: 10 },
  },
  {
    id: 'art-ice-spirit',
    name: 'Neural Chill',
    type: 'mental',
    grade: 'B',
    description: 'Lowers neural temperature to increase processing speed and defense. Perception-based.',
    realmRequirement: RealmType.Foundation,
    cost: 750,
    spiritualRoot: 'water',
    effects: { expRate: 0.38, spirit: 30, defense: 25 },
  },
  {
    id: 'art-sun-fire',
    name: 'Heliostat Mind',
    type: 'mental',
    grade: 'A',
    description: 'Focuses solar energy directly into the consciousness. Reflex-based.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3500,
    spiritualRoot: 'fire',
    effects: { expRate: 0.58, attack: 90, hp: 400 },
  },
  {
    id: 'art-earth-mountain',
    name: 'Monolithic Resolve',
    type: 'body',
    grade: 'A',
    description: 'A defensive stance that makes the user as immovable as a mountain. Hardiness-based.',
    realmRequirement: RealmType.GoldenCore,
    cost: 4000,
    spiritualRoot: 'earth',
    effects: { defense: 150, hp: 600, attack: 60 },
  },
  {
    id: 'art-golden-dragon',
    name: 'Gilded Drake',
    type: 'body',
    grade: 'A',
    description: 'A powerful high-level combat style that mimics the ferocity of a gilded mutant drake.',
    realmRequirement: RealmType.GoldenCore,
    cost: 4200,
    spiritualRoot: 'metal',
    effects: { attack: 220, defense: 80, speed: 40 },
  },
  {
    id: 'art-wood-immortal',
    name: 'Arbor Aegis',
    type: 'mental',
    grade: 'S',
    description: 'A legendary regeneration protocol that allows the user to survive indefinitely.',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    spiritualRoot: 'wood',
    effects: { expRate: 0.7, hp: 3000, defense: 200 },
  },
  {
    id: 'art-ocean-heart',
    name: 'Abyssal Heart',
    type: 'mental',
    grade: 'S',
    description: 'A deep-sea meditation technique that focuses on the crushing pressure of the depths.',
    realmRequirement: RealmType.NascentSoul,
    cost: 13000,
    spiritualRoot: 'water',
    effects: { expRate: 0.68, spirit: 1200, defense: 300 },
  },
  {
    id: 'art-phoenix-fire',
    name: 'Inferno Rebirth',
    type: 'mental',
    grade: 'S',
    description: 'Harnesses the heat of a tactical nuclear blast for rapid cellular evolution.',
    realmRequirement: RealmType.NascentSoul,
    cost: 14000,
    spiritualRoot: 'fire',
    effects: { expRate: 0.72, attack: 1800, hp: 2800 },
  },
  {
    id: 'art-earth-immortal',
    name: 'Tectonic Plate',
    type: 'body',
    grade: 'S',
    description: 'Fused with the very bedrock of the wasteland, making the user virtually indestructible.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 28000,
    spiritualRoot: 'earth',
    effects: { defense: 1500, hp: 15000, attack: 800 },
  },
  {
    id: 'art-golden-immortal',
    name: 'Auric Edge',
    type: 'body',
    grade: 'S',
    description: 'The pinnacle of metallic combat tech, capable of slicing through any composite material.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 32000,
    spiritualRoot: 'metal',
    effects: { attack: 1200, defense: 400, speed: 200 },
  },
  {
    id: 'art-five-elements',
    name: 'Omni-Element Mastery',
    type: 'mental',
    grade: 'S',
    description: 'A complete synthesis of all known wasteland elements, reaching the absolute peak of evolution.',
    realmRequirement: RealmType.DaoCombining,
    cost: 70000,
    effects: { expRate: 1.0, attack: 2000, defense: 1500, hp: 10000, spirit: 1200 },
  },
  // Rank C Arts (Scavenger)
  {
    id: 'art-sharp-blade',
    name: 'Razor Edge',
    type: 'body',
    grade: 'C',
    description: 'Condenses energy into a keen edge on melee weapons. Increases attack.',
    realmRequirement: RealmType.QiRefining,
    cost: 70,
    effects: { attack: 15 },
  },
  {
    id: 'art-thunder-palm',
    name: 'Static Discharge',
    type: 'body',
    grade: 'C',
    description: 'Builds up static electricity in the palms for a shocking strike.',
    realmRequirement: RealmType.QiRefining,
    cost: 110,
    spiritualRoot: 'metal',
    effects: { attack: 18, speed: 3 },
  },
  {
    id: 'art-wind-blade',
    name: 'Air Slicer',
    type: 'body',
    grade: 'C',
    description: 'Uses localized wind pressure to create sharp air blades. Fast and agile.',
    realmRequirement: RealmType.QiRefining,
    cost: 85,
    effects: { attack: 14, speed: 8 },
  },
  {
    id: 'art-ice-sword',
    name: 'Frost Edge',
    type: 'body',
    grade: 'C',
    description: 'Coats weapons in a layer of sub-zero frost. Chilling attacks.',
    realmRequirement: RealmType.QiRefining,
    cost: 95,
    spiritualRoot: 'water',
    effects: { attack: 16, defense: 4 },
  },
  // Rank B Arts (Wastelander)
  {
    id: 'art-blood-blade',
    name: 'Hemophage Strike',
    type: 'body',
    grade: 'B',
    description: 'Uses the users own bio-energy to create a lethal blood-stained blade. High attack.',
    realmRequirement: RealmType.Foundation,
    cost: 400,
    effects: { attack: 60 },
  },
  {
    id: 'art-lightning-strike',
    name: 'Volt Strike',
    type: 'body',
    grade: 'B',
    description: 'A powerful lightning-infused strike designed for quick termination of targets.',
    realmRequirement: RealmType.Foundation,
    cost: 450,
    spiritualRoot: 'metal',
    effects: { attack: 70, speed: 15 },
  },
  {
    id: 'art-demon-fist',
    name: 'Brute Force',
    type: 'body',
    grade: 'B',
    description: 'A savage, unrefined boxing style that uses heavy impacts. Increases attack and HP.',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    effects: { attack: 65, hp: 50 },
  },
  {
    id: 'art-frost-sword',
    name: 'Blizzard Blade',
    type: 'body',
    grade: 'B',
    description: 'A more advanced cryo-combat tech that freezes everything in its path.',
    realmRequirement: RealmType.Foundation,
    cost: 480,
    spiritualRoot: 'water',
    effects: { attack: 55, defense: 20 },
  },
  {
    id: 'art-wind-sword',
    name: 'Mach Strike',
    type: 'body',
    grade: 'B',
    description: 'Striking at ultrasonic speeds to bypass enemy defenses.',
    realmRequirement: RealmType.Foundation,
    cost: 420,
    effects: { attack: 45, speed: 25 },
  },
  {
    id: 'art-fire-blade',
    name: 'Prometheus Edge',
    type: 'body',
    grade: 'B',
    description: 'Ignites weapons with a superheated plasma field.',
    realmRequirement: RealmType.Foundation,
    cost: 380,
    spiritualRoot: 'fire',
    effects: { attack: 50, hp: 30 },
  },
  // Rank A Arts (Mutant)
  {
    id: 'art-sword-intent',
    name: 'Combat Intuition',
    type: 'body',
    grade: 'A',
    description: 'Developing a sixth sense for combat, allowing for perfect strikes. Greatly increases attack.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3200,
    effects: { attack: 250 },
  },
  {
    id: 'art-killing-intent',
    name: 'Executioners Focus',
    type: 'body',
    grade: 'A',
    description: 'A cold, calculating focus on ending the target. High attack and speed.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3600,
    effects: { attack: 280, speed: 50 },
  },
  {
    id: 'art-divine-sword',
    name: 'Omni-Blade Protocol',
    type: 'body',
    grade: 'A',
    description: 'The pinnacle of blade combat, using predictive AI to hit weaknesses.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3800,
    spiritualRoot: 'metal',
    effects: { attack: 300, defense: 100 },
  },
  {
    id: 'art-phoenix-blade',
    name: 'Inferno Raptor',
    type: 'body',
    grade: 'A',
    description: 'Mimics the movement of a legendary fiery raptor. Graceful and deadly.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3400,
    spiritualRoot: 'fire',
    effects: { attack: 260, hp: 400 },
  },
  {
    id: 'art-dragon-claw',
    name: 'Hydra Talon',
    type: 'body',
    grade: 'A',
    description: 'Attacks with multiple energy projections, tearing through targets.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3700,
    effects: { attack: 270, defense: 60 },
  },
  {
    id: 'art-void-sword',
    name: 'Event Horizon',
    type: 'body',
    grade: 'A',
    description: 'Strikes that tear through space itself. Ignoring most defenses.',
    realmRequirement: RealmType.GoldenCore,
    cost: 3900,
    effects: { attack: 320, speed: 60 },
  },
  // Rank S Arts (Legendary)
  {
    id: 'art-immortal-sword',
    name: 'Immortal Slayer Protocol',
    type: 'body',
    grade: 'S',
    description: 'A pre-war combat protocol designed to terminate high-level targets with absolute efficiency.',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 500, speed: 100 },
  },
  {
    id: 'art-lu-xian-sword',
    name: 'Executioner Protocol',
    type: 'body',
    grade: 'S',
    description: 'A relentless offensive subroutine that focuses on rapid, lethal strikes.',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 300, speed: 1000 },
  },
  {
    id: 'art-xian-xian-sword',
    name: 'Bastion Protocol',
    type: 'body',
    grade: 'S',
    description: 'A defensive subroutine that uses kinetic energy to reinforce power armor plating.',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 3000, speed: 100 },
  },
  {
    id: 'art-divine-destruction',
    name: 'Annihilation Protocol',
    type: 'body',
    grade: 'S',
    description: 'A God-Machine subroutine capable of erasing biological signatures.',
    realmRequirement: RealmType.NascentSoul,
    cost: 13000,
    effects: { attack: 1800, speed: 200, spirit: 2000 },
  },
  {
    id: 'art-celestial-blade',
    name: 'Firmament Splitter',
    type: 'body',
    grade: 'S',
    description: 'A high-powered thermal blade technique that can cut through reinforced bunkers.',
    realmRequirement: RealmType.NascentSoul,
    cost: 12000,
    spiritualRoot: 'metal',
    effects: { attack: 1600, defense: 250, speed: 150 },
  },
  {
    id: 'art-demon-god-fist',
    name: 'Titan Impact',
    type: 'body',
    grade: 'S',
    description: 'Channels massive amounts of raw energy into a single, world-shaking punch.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 28000,
    effects: { attack: 5000, hp: 3000 },
  },
  {
    id: 'art-universe-sword',
    name: 'Matter-Antimatter Edge',
    type: 'body',
    grade: 'S',
    description: 'A blade technique that utilizes balanced elemental forces to unravel matter.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 30000,
    effects: { attack: 6000, defense: 1500, speed: 1000 },
  },
  {
    id: 'art-absolute-destruction',
    name: 'Abyssal Maw',
    type: 'body',
    grade: 'S',
    description: 'The ultimate destructive potential, leaving nothing but entropy in its wake.',
    realmRequirement: RealmType.DaoCombining,
    cost: 60000,
    effects: { attack: 12000, defense: 3000, speed: 2000 },
  },
  {
    id: 'art-heaven-justice',
    name: 'Solar Overdrive',
    type: 'body',
    grade: 'S',
    description: 'A supreme technique taught by the Spirit of the Firmament, containing the purest solar energy.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 80000,
    isHeavenEarthSoulArt: true,
    bossId: 'boss_001',
    effects: { attack: 15000, defense: 5000, hp: 30000, spirit: 8000, physique: 5000 },
  },
  {
    id: 'art-earth-evil',
    name: 'Tectonic Shift',
    type: 'body',
    grade: 'S',
    description: 'A supreme technique taught by the Spirit of the Earth, containing the dark energy of the deep.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 80000,
    isHeavenEarthSoulArt: true,
    bossId: 'boss_002',
    effects: { attack: 8000, defense: 15000, hp: 40000, spirit: 6000, physique: 8000 },
  },
  {
    id: 'art-yin-yang-reincarnation',
    name: 'Binary Cycle',
    type: 'body',
    grade: 'S',
    description: 'A supreme technique taught by the Spirit of Duality, merging binary energy states. Boosts all stats significantly.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 100000,
    isHeavenEarthSoulArt: true,
    bossId: 'boss_003',
    effects: { attack: 12000, defense: 12000, hp: 50000, spirit: 10000, physique: 10000, speed: 8000 },
  },
  {
    id: 'art-chaos-primal',
    name: 'Primal Singularity',
    type: 'body',
    grade: 'S',
    description: 'A supreme technique taught by the Spirit of Chaos, harnessing the raw energy of the pre-creation state.',
    realmRequirement: RealmType.SpiritSevering,
    cost: 150000,
    isHeavenEarthSoulArt: true,
    bossId: 'boss_004',
    effects: { attack: 20000, defense: 15000, hp: 80000, spirit: 15000, physique: 12000, speed: 10000 },
  },
];

// Survival Art Battle Skill Configurations
export const CULTIVATION_ART_BATTLE_SKILLS: Record<string, BattleSkill[]> = {
  // EMP Blade Protocol - Attack Skill
  'art-thunder-sword': [
    {
      id: 'skill-thunder-sword',
      name: 'EMP Discharge',
      description: 'Injects high-voltage pulses into the blade, dealing massive damage with high crit chance.',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-thunder-sword',
      effects: [],
      cost: { mana: 30 },
      cooldown: 0,
      maxCooldown: 2,
      target: 'enemy',
      damage: {
        base: 50,
        multiplier: 1.5,
        type: 'magical',
        critChance: 0.25,
        critMultiplier: 2.0,
      },
    },
  ],
  // Bio-Regen Matrix - Heal Skill
  'art-immortal-life': [
    {
      id: 'skill-immortal-heal',
      name: 'Bio-Regen Pulse',
      description: 'Activates the regen matrix to rapidly restore health.',
      type: 'heal',
      source: 'cultivation_art',
      sourceId: 'art-immortal-life',
      effects: [],
      cost: { mana: 25 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
      heal: {
        base: 100,
        multiplier: 0.2,
      },
    },
  ],
  // Solar Pulse Fist - Attack Skill
  'art-fiery-fist': [
    {
      id: 'skill-fiery-fist',
      name: 'Solar Fist Burst',
      description: 'Channels thermal energy into double punches, dealing physical damage and potentially burning the target.',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-fiery-fist',
      effects: [
        {
          type: 'debuff',
          target: 'enemy',
          debuff: {
            id: 'burn',
            name: 'Burn',
            type: 'burn',
            value: 10,
            duration: 2,
            source: 'skill-fiery-fist',
            description: 'Target takes thermal damage over time.',
          },
        },
      ],
      cost: { mana: 20 },
      cooldown: 0,
      maxCooldown: 2,
      target: 'enemy',
      damage: {
        base: 30,
        multiplier: 1.2,
        type: 'physical',
        critChance: 0.15,
        critMultiplier: 1.8,
      },
    },
  ],
  // Core Overload - Passive Effect
  'art-pure-yang': [
    {
      id: 'skill-pure-yang-buff',
      name: 'Core Guard',
      description: 'Passive effect that boosts attack power and crit chance.',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-pure-yang',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'pure-yang-attack',
            name: 'Solar Might',
            type: 'attack',
            value: 0.15,
            duration: -1,
            source: 'art-pure-yang',
            description: 'Attack power increased by 15%',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'pure-yang-crit',
            name: 'Solar Focus',
            type: 'crit',
            value: 0.1,
            duration: -1,
            source: 'art-pure-yang',
            description: 'Crit chance increased by 10%',
          },
        },
      ],
      cost: {},
      cooldown: 0,
      maxCooldown: 0,
      target: 'self',
    },
  ],
  // Gale Dash - Speed and Crit Buff
  'art-wind-step': [
    {
      id: 'skill-wind-step',
      name: 'Wind Rider',
      description: 'Moves like the wind, increasing speed, dodge chance, and crit rate.',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-wind-step',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'wind-speed',
            name: 'Wind Speed',
            type: 'speed',
            value: 0.2,
            duration: 3,
            source: 'art-wind-step',
            description: 'Speed increased by 20% for 3 turns',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'wind-crit',
            name: 'Wind Focus',
            type: 'crit',
            value: 0.15,
            duration: 3,
            source: 'art-wind-step',
            description: 'Crit rate increased by 15% for 3 turns',
          },
        },
      ],
      cost: { mana: 20 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
    },
  ],
  // Liquid Mind - Defense Buff
  'art-water-mirror': [
    {
      id: 'skill-water-mirror',
      name: 'Liquid Mind Shield',
      description: 'Maintains a calm mind like a still lake, significantly increasing defense.',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-water-mirror',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'water-defense',
            name: 'Liquid Defense',
            type: 'defense',
            value: 0.3,
            duration: 3,
            source: 'art-water-mirror',
            description: 'Defense increased by 30% for 3 turns',
          },
        },
      ],
      cost: { mana: 25 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
    },
  ],
  // Granite Skin - Defense and Shield
  'art-earth-shield': [
    {
      id: 'skill-earth-shield',
      name: 'Granite Skin Fortification',
      description: 'Channels the stability of the earth to increase defense and create a powerful shield.',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-earth-shield',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'earth-defense',
            name: 'Granite Defense',
            type: 'defense',
            value: 0.4,
            duration: 4,
            source: 'art-earth-shield',
            description: 'Defense increased by 40% for 4 turns',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'earth-shield',
            name: 'Earthen Shield',
            type: 'shield',
            value: 200,
            duration: 4,
            source: 'art-earth-shield',
            description: 'Grants a 200 point shield for 4 turns',
          },
        },
      ],
      cost: { mana: 30 },
      cooldown: 0,
      maxCooldown: 4,
      target: 'self',
    },
  ],
  // Drake Strike - High Damage Attack
  'art-dragon-fist': [
    {
      id: 'skill-dragon-fist',
      name: 'Drake Strike',
      description: 'A powerful heavy-hitting strike that mimics a dragon, dealing massive physical damage.',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-dragon-fist',
      effects: [],
      cost: { mana: 35 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'enemy',
      damage: {
        base: 80,
        multiplier: 1.8,
        type: 'physical',
        critChance: 0.2,
        critMultiplier: 2.2,
      },
    },
  ],
  // Nova Burst - Ultimate Attack
  'art-star-destruction': [
    {
      id: 'skill-star-destruction',
      name: 'Nova Burst',
      description: 'Channels concentrated nuclear energy for a devastating strike, dealing massive magical damage.',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-star-destruction',
      effects: [],
      cost: { mana: 50 },
      cooldown: 0,
      maxCooldown: 5,
      target: 'enemy',
      damage: {
        base: 150,
        multiplier: 2.5,
        type: 'magical',
        critChance: 0.3,
        critMultiplier: 2.5,
      },
    },
  ],
};
