/**
 * Shop System Constants
 * Contains all shop definitions and shop item configurations.
 */

import { ShopType, ItemType, EquipmentSlot, RealmType, Shop } from '../types';

// --- Shop System ---

export const SHOPS: Shop[] = [
  {
    id: 'shop-village',
    name: 'Outpost General Store',
    type: ShopType.Village,
    description: 'A small outpost store selling basic survival gear and low-tier materials.',
    items: [
      {
        id: 'shop-herb-1',
        name: 'Heal Stalk',
        type: ItemType.Herb,
        description: 'A common plant used to treat minor wounds.',
        rarity: 'Common',
        price: 10,
        sellPrice: 3,
        effect: { hp: 20 },
      },
      {
        id: 'shop-material-1',
        name: 'Reinforcement Kit',
        type: ItemType.Material,
        description: 'Basic materials used to upgrade Gear.',
        rarity: 'Common',
        price: 15,
        sellPrice: 5,
      },
      {
        id: 'shop-pill-1',
        name: 'Energy Pack',
        type: ItemType.Pill,
        description: 'Briefly boosts experience gain rate.',
        rarity: 'Common',
        price: 30,
        sellPrice: 10,
        effect: { exp: 50 },
      },
      {
        id: 'shop-weapon-1',
        name: 'Wooden Club',
        type: ItemType.Weapon,
        description: 'A simple wooden club, better than nothing for a rookie.',
        rarity: 'Common',
        price: 50,
        sellPrice: 15,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 3 },
      },
    ],
  },
  {
    id: 'shop-city',
    name: 'Hub Exchange',
    type: ShopType.City,
    description: 'A bustling market in the hub city, offering a wide variety of high-quality goods.',
    items: [
      {
        id: 'shop-herb-2',
        name: 'Energy Cell',
        type: ItemType.Herb,
        description: 'A common battery, essential for crafting and survival.',
        rarity: 'Common',
        price: 20,
        sellPrice: 7,
      },
      {
        id: 'shop-pill-2',
        name: 'Rejuvenation Shot',
        type: ItemType.Pill,
        description: 'A potent medical shot that restores significant health.',
        rarity: 'Rare',
        price: 100,
        sellPrice: 30,
        effect: { hp: 200 },
      },
      {
        id: 'shop-weapon-2',
        name: 'Steel Blade',
        type: ItemType.Weapon,
        description: 'A sharp blade forged from refined steel.',
        rarity: 'Common',
        price: 150,
        sellPrice: 45,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10 },
      },
      {
        id: 'shop-armor-1',
        name: 'Scavenger Rags',
        type: ItemType.Armor,
        description: 'Simple cloth armor providing basic protection.',
        rarity: 'Common',
        price: 120,
        sellPrice: 36,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 5, hp: 20 },
      },
      {
        id: 'shop-ring-1',
        name: 'Copper Band',
        type: ItemType.Ring,
        description: 'A simple copper ring, slightly boosting attributes.',
        rarity: 'Common',
        price: 80,
        sellPrice: 24,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 2, defense: 2 },
      },
    ],
  },
  {
    id: 'shop-sect',
    name: 'Faction Armory',
    type: ShopType.Sect,
    description: 'The secure armory of a major faction, accessible only to members.',
    items: [
      {
        id: 'shop-pill-3',
        name: 'Gen-Mod Shot',
        type: ItemType.Pill,
        description: 'Permanently hardens the body, increasing max health.',
        rarity: 'Rare',
        price: 500,
        sellPrice: 150,
        effect: { hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-weapon-3',
        name: 'Cryo Blade',
        type: ItemType.Weapon,
        description: 'A sub-zero blade that can cut through reinforced plate.',
        rarity: 'Rare',
        price: 800,
        sellPrice: 240,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 15 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-armor-2',
        name: 'Combat Suit',
        type: ItemType.Armor,
        description: 'Standard issue combat suit for faction elites.',
        rarity: 'Rare',
        price: 600,
        sellPrice: 180,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 15, hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-pill-4',
        name: 'Survival Protocol',
        type: ItemType.Pill,
        description: 'Greatly increases survival odds. Grants massive experience.',
        rarity: 'Legendary',
        price: 2000,
        sellPrice: 600,
        effect: { exp: 500 },
        minRealm: RealmType.QiRefining,
      },
      {
        id: 'shop-weapon-legend',
        name: 'Plasma Sword',
        type: ItemType.Weapon,
        description: 'A legendary sword encased in superheated plasma.',
        rarity: 'Legendary',
        price: 5000,
        sellPrice: 1500,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 200, defense: 50 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-armor-legend',
        name: 'Power Armor',
        type: ItemType.Armor,
        description: 'Reinforced plating made from prime mutant scales.',
        rarity: 'Legendary',
        price: 4000,
        sellPrice: 1200,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 150, hp: 500, attack: 30 },
        minRealm: RealmType.NascentSoul,
      },
      {
        id: 'shop-accessory-1',
        name: 'Neural Charm',
        type: ItemType.Accessory,
        description: 'A neural interface charm that provides defensive feedback.',
        rarity: 'Common',
        price: 1000,
        sellPrice: 300,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { defense: 3, hp: 15 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-weapon-immortal',
        name: 'The Executioner',
        type: ItemType.Weapon,
        description: 'A mythic weapon capable of ending any life with a single strike.',
        rarity: 'Mythic',
        price: 200000,
        sellPrice: 6000,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10000, defense: 2000, hp: 5000 },
        minRealm: RealmType.SpiritSevering,
      },
      {
        id: 'shop-armor-immortal',
        name: 'Immortal Shell',
        type: ItemType.Armor,
        description: 'The ultimate protection, almost completely indestructible.',
        rarity: 'Mythic',
        price: 18000,
        sellPrice: 5400,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 800, hp: 2000, attack: 100 },
        minRealm: RealmType.SpiritSevering,
      },
    ],
  },
  {
    id: 'shop-blackmarket',
    name: 'Black Market',
    type: ShopType.BlackMarket,
    description: 'A mysterious market selling rare items at extreme prices.',
    items: [], // Items are dynamically generated via generateShopItems
    refreshCost: 1000, // Refresh cost
    refreshCooldown: 5 * 60 * 1000, // 5-minute cooldown
  },
  {
    id: 'shop-limitedtime',
    name: 'Limited Exchange',
    type: ShopType.LimitedTime,
    description: 'A daily shop with discounted high-quality gear.',
    items: [], // Items are dynamically generated via generateShopItems
    discount: 0.2, // 20% discount
    refreshCooldown: 24 * 60 * 60 * 1000, // 24-hour refresh
  },
  {
    id: 'shop-reputation',
    name: 'Reputation Store',
    type: ShopType.Reputation,
    description: 'Accessible only to those with high reputation, offering rare relics.',
    items: [], // Items are dynamically generated via generateShopItems
    reputationRequired: 100, // Requires 100 reputation points
  },
];