/**
 * Talent Traits and Titles System Constants
 */

import { Talent, Title, TitleSetEffect, EncounterEvent, ExplorationLocation, Achievement, RealmType } from '../types';

export const TALENTS: Talent[] = [
  // Common Traits (3)
  {
    id: 'talent-ordinary',
    name: 'Ordinary',
    description: 'No special traits. Just a regular survivor.',
    rarity: 'Common',
    effects: {},
  },
  {
    id: 'talent-strong-body',
    name: 'Hardy',
    description: 'Built tough. Slightly increased health.',
    rarity: 'Common',
    effects: { hp: 50 },
  },
  {
    id: 'talent-quick-learner',
    name: 'Fast Learner',
    description: 'Learns faster than most. Slightly increases experience gain.',
    rarity: 'Common',
    effects: { expRate: 0.05 },
  },

  // Rare Traits (8)
  {
    id: 'talent-spirit-root',
    name: 'Rad-Resistant',
    description: 'Natural resistance to radiation. +10% experience gain.',
    rarity: 'Rare',
    effects: { expRate: 0.1 },
  },
  {
    id: 'talent-iron-bone',
    name: 'Iron Bones',
    description: 'Dense bone structure. Increased defense and endurance.',
    rarity: 'Rare',
    effects: { defense: 30, physique: 20 },
  },
  {
    id: 'talent-sharp-blade',
    name: 'Scrapper',
    description: 'Natural combat instincts. Increased attack power.',
    rarity: 'Rare',
    effects: { attack: 40 },
  },
  {
    id: 'talent-spirit-sense',
    name: 'Keen Senses',
    description: 'Highly alert. Increased perception and speed.',
    rarity: 'Rare',
    effects: { spirit: 25, speed: 15 },
  },
  {
    id: 'talent-vitality',
    name: 'Vibrant',
    description: 'Brimming with energy. Health is greatly increased.',
    rarity: 'Rare',
    effects: { hp: 150, physique: 15 },
  },
  {
    id: 'talent-fast-cultivation',
    name: 'Survivalist Pro',
    description: 'Expert survivor. Experience gain increased by 15%.',
    rarity: 'Rare',
    effects: { expRate: 0.15 },
  },
  {
    id: 'talent-lucky',
    name: 'Lucky Find',
    description: 'Often finds good loot. Increased luck.',
    rarity: 'Rare',
    effects: { luck: 20 },
  },
  {
    id: 'talent-balanced',
    name: 'Jack of All Trades',
    description: 'Balanced development across all stats.',
    rarity: 'Rare',
    effects: {
      attack: 20,
      defense: 20,
      hp: 80,
      spirit: 15,
      physique: 15,
      speed: 10,
    },
  },

  // Legendary Traits (6)
  {
    id: 'talent-immortal-body',
    name: 'Titan Core',
    description: 'Exceptional physical structure. Greatly increased health and defense.',
    rarity: 'Legendary',
    effects: { hp: 200, defense: 50 },
  },
  {
    id: 'talent-sword-heart',
    name: 'Blade Master',
    description: 'Born for combat. Attack power greatly increased.',
    rarity: 'Legendary',
    effects: { attack: 100 },
  },
  {
    id: 'talent-thunder-body',
    name: 'Volt-Infused',
    description: 'Infused with electrical energy. Speed and attack greatly increased.',
    rarity: 'Legendary',
    effects: { attack: 80, speed: 40, spirit: 30 },
  },
  {
    id: 'talent-dragon-blood',
    name: 'Ancient Blood',
    description: 'Heir to an ancient lineage. Max HP and physique greatly increased.',
    rarity: 'Legendary',
    effects: { hp: 300, physique: 50, defense: 40 },
  },
  {
    id: 'talent-genius',
    name: 'Apocalypse Genius',
    description: 'Unmatched survival instincts. Speed and perception greatly increased.',
    rarity: 'Legendary',
    effects: { expRate: 0.25, spirit: 40 },
  },
  {
    id: 'talent-blessed',
    name: 'Fate Weaver',
    description: 'Favored by chance. Increased luck and experience gain.',
    rarity: 'Legendary',
    effects: { luck: 35, expRate: 0.15 },
  },

  // Mythic Traits (3)
  {
    id: 'talent-lucky-star',
    name: 'Chosen One',
    description: 'Fortunate destiny. Massively increased luck and experience.',
    rarity: 'Mythic',
    effects: { luck: 50, expRate: 0.2 },
  },
  {
    id: 'talent-immortal-king',
    name: 'Wasteland Legend',
    description: 'A legendary figure reborn. All stats massively increased.',
    rarity: 'Mythic',
    effects: {
      attack: 150,
      defense: 100,
      hp: 400,
      spirit: 60,
      physique: 60,
      speed: 50,
      expRate: 0.3,
    },
  },
  {
    id: 'talent-chaos-body',
    name: 'Nova Essence',
    description: 'Harnesses the power of a nova. All attributes comprehensively enhanced.',
    rarity: 'Mythic',
    effects: {
      attack: 120,
      defense: 80,
      hp: 350,
      spirit: 50,
      physique: 50,
      speed: 40,
      expRate: 0.25,
      luck: 30,
    },
  },
];

// --- Faction Titles ---
export const TITLES: Title[] = [
  {
    id: 'title-novice',
    name: 'Wasteland Rookie',
    description: 'A new face in the wastes.',
    requirement: 'Starting title',
    effects: {},
  },
  {
    id: 'title-foundation',
    name: 'Wasteland Survivor',
    description: 'Survived long enough to be considered a true denizen of the wastes.',
    requirement: 'Reach Wastelander Tier',
    effects: { attack: 10, defense: 5 },
  },
  {
    id: 'title-golden-core',
    name: 'Wasteland Veteran',
    description: 'A seasoned survivor who has seen it all.',
    requirement: 'Reach Mutant Tier',
    effects: { attack: 50, defense: 25, hp: 200 },
  },
  {
    id: 'title-nascent-soul',
    name: 'Apex Mutant',
    description: 'An evolved being at the top of the wasteland food chain.',
    requirement: 'Reach Evolved Tier',
    effects: { attack: 200, defense: 100, hp: 1000 },
  },
  {
    id: 'title-immortal',
    name: 'Transcended Entity',
    description: 'Surpassed the biological limits of the wasteland.',
    requirement: 'Reach Transcended Tier',
    category: 'cultivation',
    rarity: 'Mythic',
    effects: { attack: 1000, defense: 500, hp: 5000, expRate: 0.3 },
  },
  // Combat Titles
  {
    id: 'title-warrior',
    name: 'Brawler',
    description: 'Showed prowess in single combat.',
    requirement: 'Defeat 10 enemies',
    category: 'combat',
    rarity: 'Common',
    setGroup: 'warrior',
    effects: { attack: 15, defense: 5 },
  },
  {
    id: 'title-slayer',
    name: 'Executioner',
    description: 'A warrior feared by all in the wastes.',
    requirement: 'Defeat 50 enemies',
    category: 'combat',
    rarity: 'Rare',
    setGroup: 'warrior',
    effects: { attack: 50, defense: 20, hp: 100 },
  },
  {
    id: 'title-champion',
    name: 'Warlord',
    description: 'An unstoppable force of destruction.',
    requirement: 'Defeat 100 enemies',
    category: 'combat',
    rarity: 'Legendary',
    setGroup: 'warrior',
    effects: { attack: 150, defense: 75, hp: 500, speed: 20 },
  },
  // Exploration Titles
  {
    id: 'title-explorer',
    name: 'Scavenger',
    description: 'Always looking for something useful.',
    requirement: 'Complete 20 explorations',
    category: 'exploration',
    rarity: 'Common',
    setGroup: 'explorer',
    effects: { spirit: 10, luck: 5 },
  },
  {
    id: 'title-adventurer',
    name: 'Wasteland Explorer',
    description: 'Traveled through the most dangerous zones.',
    requirement: 'Complete 50 explorations',
    category: 'exploration',
    rarity: 'Rare',
    setGroup: 'explorer',
    effects: { spirit: 30, luck: 15, expRate: 0.1 },
  },
  {
    id: 'title-traveler',
    name: 'Pathfinder',
    description: 'Knows every inch of the wasteland.',
    requirement: 'Complete 100 explorations',
    category: 'exploration',
    rarity: 'Legendary',
    setGroup: 'explorer',
    effects: { spirit: 80, luck: 30, expRate: 0.15, speed: 15 },
  },
  // Collection Titles
  {
    id: 'title-collector',
    name: 'Tinkerer',
    description: 'Likes to collect scrap and tech.',
    requirement: 'Collect 10 types of items',
    category: 'collection',
    rarity: 'Common',
    setGroup: 'collector',
    effects: { luck: 10 },
  },
  {
    id: 'title-hoarder',
    name: 'Hoarder',
    description: 'Has a massive stash of pre-war goods.',
    requirement: 'Collect 30 types of items',
    category: 'collection',
    rarity: 'Rare',
    setGroup: 'collector',
    effects: { luck: 25, spirit: 20 },
  },
  {
    id: 'title-treasurer',
    name: 'Vault Master',
    description: 'Possesses a collection that would make even a vault overseer jealous.',
    requirement: 'Collect 50 types of items',
    category: 'collection',
    rarity: 'Legendary',
    setGroup: 'collector',
    effects: { luck: 50, spirit: 50, expRate: 0.1 },
  },
  // Special Titles
  {
    id: 'title-hermit',
    name: 'Drifter',
    description: 'A lone survivor who prefers the quiet of the wastes.',
    requirement: 'Complete 100 meditations',
    category: 'cultivation',
    rarity: 'Rare',
    effects: { expRate: 0.2, spirit: 40, physique: 30 },
  },
  {
    id: 'id-alchemist',
    name: 'Chem Expert',
    description: 'Master of creating medical supplies and stims.',
    requirement: 'Craft 20 items',
    category: 'special',
    rarity: 'Rare',
    effects: { spirit: 30, luck: 15 },
  },
  {
    id: 'title-sect-master',
    name: 'Faction Officer',
    description: 'Held a high-ranking position in a major faction.',
    requirement: 'Reach Officer rank',
    category: 'special',
    rarity: 'Legendary',
    effects: { attack: 100, defense: 100, spirit: 50, expRate: 0.15 },
  },
];

// Title Set Effects
export const TITLE_SET_EFFECTS: TitleSetEffect[] = [
  {
    setName: 'War-Torn Set',
    titles: ['title-warrior', 'title-slayer', 'title-champion'],
    description: 'Wear all brawler titles to gain massive combat bonuses.',
    effects: {
      attack: 100,
      defense: 50,
      hp: 300,
      speed: 10,
    },
  },
  {
    setName: 'Pathfinder Set',
    titles: ['title-explorer', 'title-adventurer', 'title-traveler'],
    description: 'Wear all exploration titles to boost salvage gains.',
    effects: {
      spirit: 50,
      luck: 40,
      expRate: 0.2,
      speed: 15,
    },
  },
  {
    setName: 'Vault-Tech Set',
    titles: ['title-collector', 'title-hoarder', 'title-treasurer'],
    description: 'Wear all collection titles to greatly boost luck.',
    effects: {
      luck: 80,
      spirit: 60,
      expRate: 0.15,
    },
  },
];

// --- Encounter Events ---
export const ENCOUNTER_EVENTS: EncounterEvent[] = [
  {
    id: 'encounter-herb',
    name: 'Found Tech',
    description: 'You found a piece of useful pre-war technology in the ruins.',
    rarity: 'Common',
    triggerChance: 0.3,
    rewards: {
      exp: 20,
      items: [{ name: 'Reinforcement Kit', rarity: 'Common', quantity: 1 }],
    },
  },
  {
    id: 'encounter-spirit-stone',
    name: 'Caps Cache',
    description: 'You accidentally discovered a small cache of bottle caps.',
    rarity: 'Rare',
    triggerChance: 0.15,
    rewards: {
      spiritStones: 100,
      exp: 50,
    },
  },
  {
    id: 'encounter-ancient-cave',
    name: 'Abandoned Vault',
    description: 'You found an entrance to an abandoned vault and discovered some forgotten data.',
    rarity: 'Legendary',
    triggerChance: 0.05,
    minRealm: RealmType.Foundation,
    requirements: { minLuck: 30 },
    rewards: {
      exp: 500,
      spiritStones: 500,
      items: [{ name: 'Forgotten Data Fragment', rarity: 'Legendary', quantity: 1 }],
    },
  },
  {
    id: 'encounter-immortal-herb',
    name: 'Pristine Core',
    description: 'You found a perfectly preserved energy core! This is a massive find.',
    rarity: 'Mythic',
    triggerChance: 0.01,
    minRealm: RealmType.GoldenCore,
    requirements: { minLuck: 50 },
    rewards: {
      exp: 2000,
      items: [{ name: 'Pristine Fusion Core', rarity: 'Mythic', quantity: 1 }],
    },
  },
];

// --- Exploration Locations ---
export const EXPLORATION_LOCATIONS: ExplorationLocation[] = [
  {
    id: 'explore-forest',
    name: 'Foggy Ruins',
    description: 'A city ruin covered in permanent radioactive fog. Hides many secrets.',
    minRealm: RealmType.QiRefining,
    cost: 20,
    riskLevel: 'Low',
    eventTypes: ['normal', 'lucky'],
  },
  {
    id: 'explore-mountain',
    name: 'Summit Apex',
    description: 'A towering peak reaching above the clouds, where legends say survivors have built a paradise.',
    minRealm: RealmType.Foundation,
    cost: 50,
    riskLevel: 'Medium',
    eventTypes: ['normal', 'lucky'],
    specialEncounters: ['encounter-ancient-cave'],
  },
  {
    id: 'explore-abyss',
    name: 'The Great Crater',
    description: 'A massive crater formed by a nuclear blast. High danger, even higher rewards.',
    minRealm: RealmType.GoldenCore,
    cost: 200,
    riskLevel: 'High',
    eventTypes: ['normal', 'lucky', 'secret_realm'],
    specialEncounters: ['encounter-immortal-herb'],
  },
];

// --- Achievements ---
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-step',
    name: 'First Step',
    description: 'Complete your first meditation session',
    category: 'cultivation',
    requirement: { type: 'custom', value: 1, target: 'meditate' },
    reward: { exp: 50, spiritStones: 10 },
    rarity: 'Common',
  },
  {
    id: 'ach-foundation',
    name: 'Hardened Survivor',
    description: 'Break through to the Wastelander tier',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.Foundation },
    reward: { exp: 500, spiritStones: 200, titleId: 'title-foundation' },
    rarity: 'Rare',
  },
  {
    id: 'ach-golden-core',
    name: 'Wasteland Veteran',
    description: 'Break through to the Mutant tier',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.GoldenCore },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-golden-core' },
    rarity: 'Legendary',
  },
  {
    id: 'ach-first-kill',
    name: 'Bloodied Hands',
    description: 'Defeat your first enemy during exploration',
    category: 'combat',
    requirement: { type: 'kill', value: 1 },
    reward: { exp: 100, spiritStones: 50 },
    rarity: 'Common',
  },
  {
    id: 'ach-killer-10',
    name: 'Ten Down',
    description: 'Defeat 10 enemies',
    category: 'combat',
    requirement: { type: 'kill', value: 10 },
    reward: { exp: 200, spiritStones: 100, titleId: 'title-warrior' },
    rarity: 'Common',
  },
  {
    id: 'ach-killer-50',
    name: 'Wasteland Mercenary',
    description: 'Defeat 50 enemies',
    category: 'combat',
    requirement: { type: 'kill', value: 50 },
    reward: { exp: 1000, spiritStones: 500, titleId: 'title-slayer' },
    rarity: 'Rare',
  },
  {
    id: 'ach-killer-100',
    name: 'Thousand-Cap Hunter',
    description: 'Defeat 100 enemies',
    category: 'combat',
    requirement: { type: 'kill', value: 100 },
    reward: { exp: 3000, spiritStones: 1500, titleId: 'title-champion' },
    rarity: 'Legendary',
  },
  {
    id: 'ach-collector',
    name: 'Scrapper Rookie',
    description: 'Collect 10 different types of items',
    category: 'collection',
    requirement: { type: 'collect', value: 10 },
    reward: { exp: 300, spiritStones: 200, titleId: 'title-collector' },
    rarity: 'Rare',
  },
  {
    id: 'ach-collector-20',
    name: 'Item Hoarder',
    description: 'Collect 20 different types of items',
    category: 'collection',
    requirement: { type: 'collect', value: 20 },
    reward: { exp: 500, spiritStones: 300, titleId: 'title-hoarder' },
    rarity: 'Rare',
  },
  {
    id: 'ach-collector-50',
    name: 'Vault Collector',
    description: 'Collect 50 different types of items',
    category: 'collection',
    requirement: { type: 'collect', value: 50 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-treasurer' },
    rarity: 'Legendary',
  },
  {
    id: 'ach-adventure-20',
    name: 'Exploring the Waste',
    description: 'Complete 20 explorations',
    category: 'exploration',
    requirement: { type: 'adventure', value: 20 },
    reward: { exp: 300, spiritStones: 150, titleId: 'title-explorer' },
    rarity: 'Common',
  },
  {
    id: 'ach-adventure-50',
    name: 'Ruins Veteran',
    description: 'Complete 50 explorations',
    category: 'exploration',
    requirement: { type: 'adventure', value: 50 },
    reward: { exp: 800, spiritStones: 400, titleId: 'title-adventurer' },
    rarity: 'Rare',
  },
  {
    id: 'ach-adventure-100',
    name: 'Legendary Pathfinder',
    description: 'Complete 100 explorations',
    category: 'exploration',
    requirement: { type: 'adventure', value: 100 },
    reward: { exp: 1500, spiritStones: 800, titleId: 'title-traveler' },
    rarity: 'Rare',
  },
  {
    id: 'ach-meditate-100',
    name: 'Internal Balance',
    description: 'Complete 100 meditation sessions',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 100 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-hermit' },
    rarity: 'Legendary',
  },
  {
    id: 'ach-equip-5',
    name: 'Fully Equipped',
    description: 'Equip 5 different items',
    category: 'collection',
    requirement: { type: 'equip', value: 5 },
    reward: { exp: 200, spiritStones: 100 },
    rarity: 'Common',
  },
  {
    id: 'ach-pet-1',
    name: 'Mutant Companion',
    description: 'Obtain your first mutant pet',
    category: 'special',
    requirement: { type: 'pet', value: 1 },
    reward: { exp: 500, spiritStones: 200 },
    rarity: 'Rare',
  },
  {
    id: 'ach-pet-3',
    name: 'Beast Master',
    description: 'Obtain 3 different mutant pets',
    category: 'special',
    requirement: { type: 'pet', value: 3 },
    reward: { exp: 1500, spiritStones: 800 },
    rarity: 'Legendary',
  },
  {
    id: 'ach-recipe-5',
    name: 'Chemist Apprentice',
    description: 'Unlock 5 different crafting recipes',
    category: 'collection',
    requirement: { type: 'recipe', value: 5 },
    reward: { exp: 400, spiritStones: 200 },
    rarity: 'Rare',
  },
  {
    id: 'ach-art-3',
    name: 'New Protocols',
    description: 'Learn 3 different techniques',
    category: 'cultivation',
    requirement: { type: 'art', value: 3 },
    reward: { exp: 600, spiritStones: 300 },
    rarity: 'Rare',
  },
  {
    id: 'ach-art-10',
    name: 'Protocol Master',
    description: 'Learn 10 different techniques',
    category: 'cultivation',
    requirement: { type: 'art', value: 10 },
    reward: { exp: 3000, spiritStones: 1500 },
    rarity: 'Legendary',
  },
  {
    id: 'ach-breakthrough-5',
    name: 'Evolving Fast',
    description: 'Complete 5 successful breakthroughs',
    category: 'cultivation',
    requirement: { type: 'breakthrough', value: 5 },
    reward: { exp: 1000, spiritStones: 500 },
    rarity: 'Rare',
  },
  {
    id: 'ach-secret-realm-5',
    name: 'Vault Dweller Explorer',
    description: 'Enter 5 different secret realms',
    category: 'exploration',
    requirement: { type: 'secret_realm', value: 5 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: 'Legendary',
  },
  {
    id: 'ach-lottery-10',
    name: 'Gambler',
    description: 'Use the recruitment system 10 times',
    category: 'special',
    requirement: { type: 'lottery', value: 10 },
    reward: { exp: 300, spiritStones: 200 },
    rarity: 'Common',
  },
  {
    id: 'ach-lottery-50',
    name: 'High Roller',
    description: 'Use the recruitment system 50 times',
    category: 'special',
    requirement: { type: 'lottery', value: 50 },
    reward: { exp: 2000, spiritStones: 1500 },
    rarity: 'Rare',
  },
  {
    id: 'ach-alchemy-20',
    name: 'Master Chemist',
    description: 'Successfully craft 20 items',
    category: 'special',
    requirement: { type: 'custom', value: 20, target: 'alchemy' },
    reward: { exp: 1000, spiritStones: 1000, titleId: 'id-alchemist' },
    rarity: 'Legendary',
  },
  {
    id: 'ach-sect-master',
    name: 'Faction Pillar',
    description: 'Promoted to Officer rank or higher within a faction',
    category: 'special',
    requirement: { type: 'custom', value: 1, target: 'sect_elder' },
    reward: { exp: 2000, spiritStones: 2000, titleId: 'title-sect-master' },
    rarity: 'Legendary',
  },
];
